In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print("Numpy Version:",np.__version__)
print("Pandas Version:",pd.__version__)
print("Setup Complete!Everything is ready to use.")

Numpy Version: 2.3.5
Pandas Version: 2.3.3
Setup Complete!Everything is ready to use.


In [2]:
a=np.array([1,2,3,4,5,6,7])
print(a)
print(type(a))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [3]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
c=np.array([[[1,2,3],[4,5,6]],[[9,8,0],[7,6,3]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[9 8 0]
  [7 6 3]]]


In [5]:
d=np.array([2,4,7],dtype=float)
print(d)

[2. 4. 7.]


In [6]:
e=np.array([2,5,8],dtype=bool)
print(e)

[ True  True  True]


In [7]:
f=np.array([5,5,6],dtype=complex)
print(f)

[5.+0.j 5.+0.j 6.+0.j]


In [8]:
g=np.array([24,56,87],dtype=int)
print(g)

[24 56 87]


In [9]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a=np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [11]:
c=np.arange(1,11,2)
print(c)
c=np.arange(1,11,2).reshape(2,5)
print(c)

[1 3 5 7 9]


ValueError: cannot reshape array of size 5 into shape (2,5)

In [12]:
c=np.arange(1,11)
print(c)
c=np.arange(1,11).reshape(2,5)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
c=np.arange(1,11,2)
print(c)
c=np.arange(1,11,2).reshape(5,1)
print(c)

[1 3 5 7 9]
[[1]
 [3]
 [5]
 [7]
 [9]]


In [14]:
p=np.zeroes(4,4)
print(p)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [15]:
p=np.zeros(4,4)
print(p)

TypeError: Cannot interpret '4' as a data type

In [16]:
p=np.zeros(4)
print(p)

[0. 0. 0. 0.]


In [17]:
p=np.zeros((4,4))
print(p)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
p=np.ones((3,3))
print(p)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
p=np.zeros((2,3))
print(p)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
p=np.ones((4,5))
print(p)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
p=np.identity(3)
print(p)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
p=np.identity(5)
print(p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
c=np.linespace(1,17,5)
print(c)

AttributeError: module 'numpy' has no attribute 'linespace'

In [24]:
c=np.linspace(1,17,5)
print(c)

[ 1.  5.  9. 13. 17.]


In [25]:
c=np.linspace(-10,10,10,dtype=int)
print(c)

[-10  -8  -6  -4  -2   1   3   5   7  10]


In [26]:
c=np.linspace(-10,10,10)
print(c)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [1]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

NameError: name 'np' is not defined

In [2]:
import numpy as np
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
a1.ndim

1

In [5]:
a2.ndim


2

In [6]:
a3.ndim

3

In [7]:
a1.shape

(10,)

In [8]:
a2.shape

(3, 4)

In [9]:
a3.shape

(2, 2, 2)

In [10]:
a1.size

10

In [11]:
a2.size


12

In [12]:
a3.size

8

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2.dtype

dtype('float64')

In [15]:
a3.dtype

dtype('int64')

In [16]:
a1.itemsize

8

In [17]:
a1.nbytes

80

In [18]:
a2.nbytes

96

In [19]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [20]:
p=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(p)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [21]:
p[1]

array([5, 6, 7, 8])

In [22]:
p[0:3,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
p[0:3,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [24]:
p[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [26]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
print(a2[:,0:3])

[[1 2 3]
 [5 6 7]]


In [27]:
a=np.array([1,2,3,4])
b=np.array([7,8,9,10])
print(a)
print(b)

[1 2 3 4]
[ 7  8  9 10]


In [28]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 8 10 12 14]
[-6 -6 -6 -6]
[ 7 16 27 40]
[0.14285714 0.25       0.33333333 0.4       ]


In [29]:
print(a%b)

[1 2 3 4]


In [30]:
b=np.array([8,10.12,14])
print(b+2)
print(b*2)
print(b/2)
print(b%2)


[10.   12.12 16.  ]
[16.   20.24 28.  ]
[4.   5.06 7.  ]
[0.   0.12 0.  ]


In [31]:
b=np.array([8,10,12,14])
print(b+2)
print(b*2)
print(b/2)
print(b%2)


[10 12 14 16]
[16 20 24 28]
[4. 5. 6. 7.]
[0 0 0 0]


In [35]:
c=np.array([10,20,30,40,50])
print(np.median(c))

30.0


In [36]:
print(np.max(c))

50


In [37]:
print(np.min(c))

10


In [38]:
print(np.sum(c))

150


In [39]:
print(np.std(c))

14.142135623730951


In [40]:
print(np.var(c))

200.0


In [41]:
c=np.array([4,9,12])
print(c)

[ 4  9 12]


In [42]:
print(np.power(c,3))

[  64  729 1728]


In [43]:
print(np.sqrt(c))

[2.         3.         3.46410162]


In [44]:
print(np.square(c))

[ 16  81 144]


In [45]:
print(np.absolute(c))

[ 4  9 12]


In [46]:
print(np.abs(c))

[ 4  9 12]


In [48]:
p=np.array([8,10,12])
print(np.log(p))
print(np.log10(p))
print(np.exp(p))

[2.07944154 2.30258509 2.48490665]
[0.90308999 1.         1.07918125]
[  2980.95798704  22026.46579481 162754.791419  ]


In [49]:
m=np.array([[1,2,3],[4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [50]:
print(np.sum(m,axis=0))

[5 7 9]


In [51]:
print(np.sum(m,axis=1))

[ 6 15]


In [52]:
print(np.min(m,axis=0))

[1 2 3]


In [53]:
print(np.max(m,axis=0))

[4 5 6]


In [54]:
print(np.sum(m,axis=0))
print(np.sum(m,axis=1))

[5 7 9]
[ 6 15]


In [55]:
print(np.max(m,axis=0))
print(np.max(m,axis=1))

[4 5 6]
[3 6]


In [56]:
print(np.mean(m,axis=0))
print(np.mean(m,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [57]:
print(np.median(m,axis=0))
print(np.median(m,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [58]:
print(np.var(m,axis=0))
print(np.var(m,axis=1))
print(np.std(m,axis=0))
print(np.std(m,axis=1))

[2.25 2.25 2.25]
[0.66666667 0.66666667]
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [59]:
print(np.power(m,3,axis=0))

TypeError: power() got an unexpected keyword argument 'axis'

In [60]:
print(np.square(m,axis=0))

TypeError: square() got an unexpected keyword argument 'axis'

In [61]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [62]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [63]:
np.t(a)

AttributeError: module 'numpy' has no attribute 't'

In [64]:
np.T(a)

AttributeError: module 'numpy' has no attribute 'T'

In [65]:
print(a.t)

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [66]:
print(a.T)

[[1 3]
 [2 4]]


In [70]:
a=np.array([[1,2],[5,6]])
b=np.array([[10,20],[50,60]])
print(a)
print(b)


[[1 2]
 [5 6]]
[[10 20]
 [50 60]]


In [71]:
np.add(a,b)

array([[11, 22],
       [55, 66]])

In [73]:
a+b

array([[11, 22],
       [55, 66]])

In [74]:
a-b

array([[ -9, -18],
       [-45, -54]])

In [75]:
a*b

array([[ 10,  40],
       [250, 360]])

In [76]:
a@b

array([[110, 140],
       [350, 460]])

In [77]:
np.dot(a,b)

array([[110, 140],
       [350, 460]])

In [78]:
a.T

array([[1, 5],
       [2, 6]])

In [79]:
b.T

array([[10, 50],
       [20, 60]])

In [81]:
np.linalg.det(a)

np.float64(-3.999999999999999)

In [82]:
np.linalg.det(b)

np.float64(-399.9999999999999)

In [83]:
np.linalg.inv(a)

array([[-1.5 ,  0.5 ],
       [ 1.25, -0.25]])

In [84]:
np.linalg.inv(b)

array([[-0.15 ,  0.05 ],
       [ 0.125, -0.025]])

In [85]:
np.dot(a,np.linalg.inv(a))

array([[1., 0.],
       [0., 1.]])

In [86]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [3]:
print(a+b)
print(a-b)
print(a*b)
print(a@b)
print(np.dot(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [4]:
print(np.linalg.det(a))
print(np.linalg.det(b))

-2.0000000000000004
-1.999999999999999


In [5]:
print(np.linalg.inv(a))
print(np.linalg.inv(b))
print(a@np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-4.   3. ]
 [ 3.5 -2.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [6]:
print(np.dot(a,np.linalg.inv(a)))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [7]:
c=np.array([[1,2],[2,4]])
print(np.linalg.matrix_rank(c))

1


In [8]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [9]:
print(np.mul(c,axis=0))

AttributeError: module 'numpy' has no attribute 'mul'

In [10]:
print(np.random.rand(5))

[0.93661012 0.09369108 0.529864   0.29972908 0.63586703]


In [11]:
print(np.random.randn(5))

[-0.00311336  0.79215343 -0.45663886 -1.01871771 -0.04546518]


In [12]:
np.random.randint(1,100,size=10)

array([21, 27, 60, 79, 24, 12, 33, 75,  2,  3], dtype=int32)

In [14]:
print(np.random.seed(42))

None


In [15]:
np.random.rand(5)
np.random.rand(2,3)

array([[0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449]])

In [16]:
np.random.randint(1,100)

2

In [17]:
np.random.randint(1,100,size=5)

array([88, 30, 38,  2, 64], dtype=int32)

In [19]:
np.random.randint(1,100,size=(10,5))

array([[60, 21, 33, 76, 58],
       [22, 89, 49, 91, 59],
       [42, 92, 60, 80, 15],
       [62, 62, 47, 62, 51],
       [55, 64,  3, 51,  7],
       [21, 73, 39, 18,  4],
       [89, 60, 14,  9, 90],
       [53,  2, 84, 92, 60],
       [71, 44,  8, 47, 35],
       [78, 81, 36, 50,  4]], dtype=int32)

In [20]:
np.random.rand(5)

array([0.31171108, 0.52006802, 0.54671028, 0.18485446, 0.96958463])

In [21]:
np.random.rand(5)

array([0.77513282, 0.93949894, 0.89482735, 0.59789998, 0.92187424])

In [22]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [23]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [24]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [25]:
np.random.seed(24)
np.random.rand(5)

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 , 0.36105635])

In [26]:
np.random.seed(24)
np.random.rand(5)

array([0.9600173 , 0.69951205, 0.99986729, 0.2200673 , 0.36105635])

In [32]:
a=np.array([2,3,4,5,6,7,8,9,10])
b=np.random.shuffle(a)
print(b)

None


In [29]:
print(np.random.shuffle(a))

None


In [30]:
a=np.array([1,2,3,4,5])
b=np.random.permutation(a)

In [31]:
print(b)

[3 4 1 5 2]


In [33]:
a=np.random.randint(1,100)
print(a)

28


In [34]:
a=np.random.randint(1,100,size=10)

In [35]:
print(a)

[98 34  4  5 66 11 42 57 46  8]


In [36]:
np.random.randint(1,100,size=(3,3))

array([[ 6, 61, 84],
       [43,  1, 28],
       [22, 67, 37]], dtype=int32)

In [37]:
np.random.randn(5)

array([ 0.14954999, -1.59160088,  1.09685389, -0.75307901,  0.87670806])

In [38]:
a=np.array([1,2,3,4,5])
print(np.random.shuffle(a))

None


In [39]:
np.random.seed(42)
np.random.randint(1,100,size=5)

array([52, 93, 15, 72, 61], dtype=int32)

In [40]:
np.random.seed(42)
np.random.randint(5)

3

In [41]:
np.random.seed(42)
np.random.randint(1,100,size=5)

array([52, 93, 15, 72, 61], dtype=int32)

In [42]:
a=np.array([10,20,30,40,50])
print(np.random.choice(a,size=3))

[50 20 30]


In [43]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [45]:
print(np.argmax(a))
print(np.argmin(a))

9
0


In [46]:
a>25

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [47]:
a[a>25]

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [49]:
print(a>=30)

[False False  True  True  True  True  True  True  True  True]


In [50]:
print(a[a>=30])

[ 30  40  50  60  70  80  90 100]


In [51]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
print(a)
print(np.argmax(a))
print(np.argmin(a))

[ 10  20  30  40  50  60  70  80  90 100]
9
0


In [52]:
print(a>20)
print(a[a>20])

[False False  True  True  True  True  True  True  True  True]
[ 30  40  50  60  70  80  90 100]


In [53]:
print(a<30)
print(a[a<30])

[ True  True False False False False False False False False]
[10 20]


In [54]:
print(a==30)
print(a[a==30])

[False False  True False False False False False False False]
[30]


In [55]:
print(a>=20)
print(a[a>=20])

[False  True  True  True  True  True  True  True  True  True]
[ 20  30  40  50  60  70  80  90 100]


In [56]:
print(a<=30)
print(a[a<=30])

[ True  True  True False False False False False False False]
[10 20 30]


In [57]:
print(a!=20)
print(a[a!=20])

[ True False  True  True  True  True  True  True  True  True]
[ 10  30  40  50  60  70  80  90 100]


In [58]:
a>20 & a<80

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [61]:
print(a[(a>20) & (a<70)])

[30 40 50 60]


In [62]:
(a>20) & (a<70)

array([False, False,  True,  True,  True,  True, False, False, False,
       False])

In [63]:
(a<20)|(a>70)

array([ True, False, False, False, False, False, False,  True,  True,
        True])

In [66]:
a=[10,20,30,40,50,60,70,80,90,100]
a[~(a>25)]

TypeError: '>' not supported between instances of 'list' and 'int'

In [67]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [68]:
~(a>25)

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [69]:
a[~(a>30)]

array([10, 20, 30])

In [70]:
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [71]:
a>20

array([[False, False,  True],
       [ True,  True,  True]])

In [72]:
a[a>20]

array([30, 40, 50, 60])

In [73]:
a==20

array([[False,  True, False],
       [False, False, False]])

In [74]:
a[a==20]

array([20])

In [75]:
a[(a>20)&(a<70)]

array([30, 40, 50, 60])

In [76]:
a[~(a>50)]

array([10, 20, 30, 40, 50])

In [77]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [78]:
np.reshape(5,1)

array([5])

In [79]:
print(np.reshape(5,1))

[5]


In [80]:
a.shape(5,1)

TypeError: 'tuple' object is not callable

In [81]:
a.shape

(5,)

In [82]:
a.reshape(-1,1)

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [83]:
a.reshape(1,-1)

array([[10, 20, 30, 40, 50]])

In [84]:
import numpy as np
import pandas as pd


In [85]:
a=np.arange(1,11)

In [86]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [87]:
a=np.zeros(10)

In [88]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
a=np.arange(2,22,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [92]:
c=np.arange(10,55,5)
print(c)

[10 15 20 25 30 35 40 45 50]


In [95]:
c=np.ones(9).reshape(3,3)
print(c)
c=c*7
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [96]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [97]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [99]:
a=np.array([[1,2,3,4,5],[4,5,6,7,9]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 9]]


In [101]:
a.shape

(2, 5)

In [102]:
a.ndim

2

In [2]:
import numpy as np
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
a[0:5]

array([1, 2, 3, 4, 5])

In [5]:
a[15:21]

array([16, 17, 18, 19, 20])

In [6]:
a[5:11]

array([ 6,  7,  8,  9, 10, 11])

In [7]:
a[-1:-20]

array([], dtype=int64)

In [8]:
a[-20:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
a[0:20:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [12]:
a[0:3]=100

In [13]:
print(a)

[100 100 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [16]:
b=np.arange(1,13).reshape(3,4)

In [17]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
b[1,2]

np.int64(7)

In [21]:
b[1,:]

array([5, 6, 7, 8])

In [22]:
b[:,2]

array([ 3,  7, 11])

In [24]:
b[:1,:1]

array([[1]])

In [25]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [26]:
print(np.sum(a))

210


In [27]:
print(np.mean(a))

35.0


In [28]:
print(np.median(a))

35.0


In [29]:
print(np.max(a))
print(np.min(a))

60
10


In [30]:
print(np.argmax(a))

5


In [31]:
print(np.std(a))

17.07825127659933


In [37]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(np.sum(a,axis=1))

[ 6 15 24]


In [38]:
print(np.mean(a,axis=0))

[4. 5. 6.]


In [39]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [40]:
print(a[a>10])

[11 12 13 14 15 16 17 18 19 20]


In [41]:
a[a%2==0]=0

In [42]:
print(a)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


In [43]:
a[(a%2==0)&(a%3==0)]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [45]:
print(a[(a%2==0)&(a%3==0)])

[ 6 12 18]


In [47]:
a[a>10]=1

In [48]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10  1  1  1  1  1  1  1  1  1  1]


In [50]:
a[a<=10]=0

In [51]:
print(a)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [52]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [53]:
np.where(a>10,1,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
import pandas as pd


In [55]:
dict={
    "NAME":['ANUBHAV','ACHARYA','SNEHA','TRIPATHY','SAISHREE','PADHY'],
    "MARKS":[90,82,91,100,80,100],
    "CITY":['JAMSHEDPUR','TATANAGAR','BHUBANESWAR','JAJPUR','NUAPADA','SAMBALPUR']
}
print(dict)

{'NAME': ['ANUBHAV', 'ACHARYA', 'SNEHA', 'TRIPATHY', 'SAISHREE', 'PADHY'], 'MARKS': [90, 82, 91, 100, 80, 100], 'CITY': ['JAMSHEDPUR', 'TATANAGAR', 'BHUBANESWAR', 'JAJPUR', 'NUAPADA', 'SAMBALPUR']}


In [56]:
df=pd.DataFrame(dict)

In [57]:
print(df)

       NAME  MARKS         CITY
0   ANUBHAV     90   JAMSHEDPUR
1   ACHARYA     82    TATANAGAR
2     SNEHA     91  BHUBANESWAR
3  TRIPATHY    100       JAJPUR
4  SAISHREE     80      NUAPADA
5     PADHY    100    SAMBALPUR


In [59]:
df.to_csv('FRIENDS.csv')